jdbc:
  url: jdbc:mysql://localhost:3306/catering?allowPublicKeyRetrieval=true&useSSL=false
  user: sdim2087
  passwd: 1234
  database: catering
  poolSize: 10
  driver: com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/catering?allowPublicKeyRetrieval=true&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: sdim2087
    password: 1234
    name: catering
    poolSize: 10
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
